apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
spec:
  type: NodePort
  selector:
    app: "{{ .Release.Name }}"
  ports:
    - port: {{ .Values.service.port | int }}
      targetPort: {{ .Values.service.port | int }}
      nodePort: {{ .Values.service.nodePort | int }}
